### PR TITLE
add support for all ITM packet types and replace Decoder with Stream parser

### PR DESCRIPTION
**Pull request by japaric**
as this is a breaking change and requires a minor version bump, this commit
also:

- sets MSRV to 1.31.0
- changes the crate edition to 2018
- removes `itmdump` (more info below)

---

The rationale for dropping the existing `Decoder` API is that it doesn't handle
well streams of data that contain errors, like missing bytes (occurs in ~0.2% of
packets according to my unscientific measurements). Namely, `Decoder` can't
backtrack the stream because it has no internal buffer; meaning that once a byte
is lost it will continue to parse packets with an offset of one (i.e. the first
byte of the payload will be treated as the packet header) leading to a cascade
of errors.

The `Stream` API has an internal buffer so when it encounters a packet error due
to a missing byte it can backtrack the stream and retry parsing from the most
likely place. Also, thanks to the internal buffer `Stream` greatly reduces the
number of read syscalls -- the `Decoder` API was doing 1-byte read syscalls in
some places.

(For historic purposes, I have pushed [the branch] where I was adding full
parsing support to the `Decoder` API)

[the branch]: https://github.com/rust-embedded/itm/tree/decoder

With this new API and support for all the different ITM packets I have created a
set of tools ([`itm-tools`]) for analyzing ITM traces. One of the tools,
`port-demux`, is a more general version of `itmdump` and should be preferred
over it. The other reason for removing `itmdump` and not providing tools in this
crate is that it makes version management easier: breaking changes in the
library don't necessarily mean breaking changes in the tool CLI.

[`itm-tools`]: https://github.com/japaric/itm-tools

r? @rust-embedded/tools
cc @rust-embedded/cortex-m

### CODE REVIEW

**Comment by korken89** [comment]
Sorry for the late reply!

Overall I like this update, I have had strange things happen with ITM before but never looked into it. With this change we should be getting closer to production ready tools in this area, great job!

**Comment by japaric** [comment]
@rust-embedded/tools any thoughts about this PR?

**Comment by therealprof** [comment]
I don't have time to test AT>M but it looks good.

**Comment by korken89** [comment]
@rust-embedded/tools time to move this forward?

**Pull request merged**
